const en = {
  nav: {
    home: "Home",
    solutions: "Solutions",
    projects: "Projects",
    sectors: "Sectors",
    cta: "Get a Quote",
  },
  clip: {
    tagline: "Next-Gen Digital Strategist",
  },
  hero: {
    badge: "Your Digital Transformation Partner",
    h1_1: "The ",
    h1_2: "AI-Powered ",
    h1_3: "Digital Partner ",
    h1_4: "for Modern Businesses",
    subtitle:
      "I help businesses grow with AI-driven strategies, modern web technologies, and data-centric approaches.",
    btnProjects: "Explore Projects",
    btnContact: "Get in Touch",
    scroll: "Scroll",
  },
  solutions: {
    badge: "Strategic Solutions",
    heading1: "Comprehensive Solutions",
    heading2: "for Your Digital Growth",
    subtitle:
      "Take your business to the next level with end-to-end digital transformation services.",
    items: [
      {
        title: "Corporate Web Solutions",
        description:
          "Building modern, enterprise-grade, fully SEO-compliant websites, hosting them on secure servers, and managing all technical maintenance processes.",
      },
      {
        title: "GEO & AI Strategy",
        description:
          "Applying GEO (Generative Engine Optimization) in the age of AI to make companies stand out in next-generation AI-powered search engines.",
      },
      {
        title: "Corporate Media & Design",
        description:
          "Professional-level video editing, social media management, and high-quality graphic design aligned with your brand identity.",
      },
      {
        title: "Next.js Corporate Identity",
        description:
          "Ultra-fast, SEO-friendly, and scalable modern corporate portfolios built from scratch with Next.js architecture.",
      },
      {
        title: "In-House Business Automation",
        description:
          "Custom desktop/web automation tools and comprehensive management panels built with C# and Python to accelerate internal workflows.",
      },
      {
        title: "Data Dashboards & Reporting",
        description:
          "Custom dashboards and reporting interfaces that transform business data into meaningful metrics and accelerate decision-making.",
      },
    ],
  },
  projects: {
    badge: "PORTFOLIO",
    heading1: "Featured",
    heading2: "Projects",
    freelanceTitle: "Freelance Script & Solution Archive",
    freelanceDesc:
      "Niche industry software developed on-demand on freelance platforms in the past, expanding my portfolio and sector expertise.",
    confidentialBanner:
      "Real mechanical and interface photos cannot be shared due to competition confidentiality policies. Visuals are theoretical AI-generated concepts.",
    confidentialTitle: "Competition Confidentiality",
    confidentialModal:
      "This visual is a theoretical concept generated by AI in compliance with competition rules.",
    showDetails: "Explore System Features",
    hideDetails: "Hide Details",
    items: [
      {
        title: "Stock Analysis Bot",
        category: "AI-POWERED FINANCE",
        description:
          "An advanced AI platform that analyzes BIST stocks using LightGBM machine learning, Triple-Barrier labeling, and Purged K-Fold CV.",
        techInfo:
          "Binary classification with LightGBM, 150+ technical indicators, automatic pattern detection, and sector heat maps.",
        role: "Full-stack development — backend API, ML pipeline, frontend dashboard, and real-time data streaming.",
        result:
          "Real-time technical analysis for 417+ BIST stocks, AI signal generation, and automatic pattern recognition.",
        expandedContent: [
          {
            title: "Automatic Pattern Detection",
            desc: "Simultaneously scans 13 different technical patterns (Double Top, Head & Shoulders, etc.) on charts and marks them with confidence scores.",
          },
          {
            title: "Machine Learning & Prediction",
            desc: "Generates directional predictions (BUY/SELL/HOLD) using custom labeling techniques (Triple-Barrier) and Ensemble models.",
          },
          {
            title: "Natural Language Processing (NLP)",
            desc: "Simultaneously fetches market news, performs sentiment analysis, and blends results with technical data.",
          },
          {
            title: "Dynamic Risk Management",
            desc: "Autonomously adjusts model decision thresholds based on market volatility to preserve the risk/reward ratio.",
          },
        ],
      },
      {
        title: "Vibe Coach",
        category: "AI EDUCATION PLATFORM",
        description:
          "A SaaS EdTech platform offering a personalized AI Education Coach for every student. Gamifies learning with behavioral analytics, exam simulations, 1v1 duels, and a league system.",
        techInfo:
          "React 19 + Vite frontend, Node.js + TypeScript backend, MySQL + Kysely query builder, Redis caching, Socket.io real-time, and Google Gemini (2.0 Flash + 1.5 Pro) hybrid AI engine.",
        role: "Full-stack development — AI coaching engine, Vibe Analytics behavioral analysis algorithms, exam simulator, and gamification systems.",
        result:
          "Success projection (Linear Regression), burnout detector, ÖSYM-style question generation, and 99.9% AI service uptime.",
        expandedContent: [
          {
            title: "Vibe Analytics",
            desc: "30-day success projection via Linear Regression, burnout detection through speed-accuracy correlation, and time efficiency indexing.",
          },
          {
            title: "Smart Exam Simulation",
            desc: "AI-generated questions mimicking real ÖSYM/MEB exam styles and Normal Distribution-based dynamic difficulty scaling.",
          },
          {
            title: "Gamification & Duels",
            desc: "Weekly league cycles from Bronze to Champions League, Socket.io-powered 1v1 real-time duels, and streak mechanics.",
          },
          {
            title: "Institutional (B2B) Analytics",
            desc: "At-risk student detection for schools and tutoring centers, class-level topic heatmaps, and an administrator dashboard.",
          },
        ],
      },
      {
        title: "UMAY Search & Rescue UAV",
        category: "AUTONOMOUS UAV SYSTEM",
        description:
          "An autonomous hexacopter system with dual sensors (Thermal + RGB) and AI, providing aerial strategic support to search-and-rescue teams like AFAD and JAK.",
        techInfo:
          "Live target detection via YOLO-based image processing, Thermal and RGB camera fusion, autonomous route planning.",
        role: "Systems Engineering & Computer Vision — autonomous flight algorithms, sensor integration, and target detection.",
        result:
          "A prototype capable of autonomous transit, precise payload delivery to targets, and live detection even in complete darkness.",
        expandedContent: [
          {
            title: "Autonomous Transit & Reconnaissance",
            desc: "GPS-guided flight to disaster zones and algorithmic search-and-scan route generation without any pilot intervention.",
          },
          {
            title: "Sensor Fusion",
            desc: "High-accuracy live detection in complete darkness, dense fog, or smoke using a hybrid Thermal + RGB camera.",
          },
          {
            title: "Precise Autonomous Intervention",
            desc: "Autonomous, millimeter-precise payload delivery after AI-based detection of marked supply packages.",
          },
          {
            title: "Psychological First Aid",
            desc: "Providing aerial psychological first aid to survivors via the drone's on-board public announcement and audio system.",
          },
        ],
      },
    ],
    labels: {
      techStack: "TECH STACK",
      role: "ROLE",
      result: "RESULT",
      demo: "DEMO",
    },
  },
  marquee: {
    badge: "Sector Solutions",
    heading1: "Digital Modules",
    heading2: "for Every Sector",
    subtitle:
      "Ready-made and customizable digital solutions tailored to your industry.",
    items: [
      { title: "E-Commerce", description: "Online sales platforms and payment integrations" },
      { title: "QR Menu", description: "Digital menu solutions for restaurants and cafes" },
      { title: "Booking System", description: "Online appointment and calendar management" },
      { title: "CRM", description: "Customer relationship management systems" },
      { title: "Education Platform", description: "Online learning and LMS solutions" },
      { title: "Logistics", description: "Cargo tracking and fleet management systems" },
      { title: "Healthcare", description: "Patient tracking and healthcare service management" },
      { title: "Finance", description: "Financial analysis and payment infrastructure" },
    ],
  },
  footer: {
    tagline: "Next-Gen Digital Strategist",
    copyright: "All rights reserved.",
  },
};

export default en;
