const en = {
  nav: {
    home: "Home",
    solutions: "Solutions",
    projects: "Projects",
    sectors: "Sectors",
    cta: "Get a Quote",
  },
  clip: {
    tagline: "Software Developer",
  },
  hero: {
    badge: "Full-Stack Developer & GEO Strategist",
    h1_1: "Alperen ",
    h1_2: "Bozkurt",
    h1_3: "",
    h1_4: "",
    subtitle:
      "I blend my passion for software with academic foundations in computer programming and a vision of becoming a comprehensive full-stack developer. Beyond code, I produce projects in creative fields like graphic design and video editing, while deeply researching technological innovations. Maintaining my discipline and energy through fitness, I aim to create innovative and optimized solutions by merging technical excellence with an aesthetic perspective.",
    btnProjects: "Explore Projects",
    btnContact: "Get in Touch",
    scroll: "Scroll",
  },
  solutions: {
    badge: "Strategic Solutions",
    heading1: "Comprehensive Solutions",
    heading2: "for Your Digital Growth",
    subtitle:
      "Take your business to the next level with end-to-end digital transformation services.",
    items: [
      {
        title: "Corporate Web Solutions",
        description:
          "Building modern, enterprise-grade, fully SEO-compliant websites, hosting them on secure servers, and managing all technical maintenance processes.",
      },
      {
        title: "GEO & AI Strategy",
        description:
          "Applying GEO (Generative Engine Optimization) in the age of AI to make companies stand out in next-generation AI-powered search engines.",
      },
      {
        title: "Corporate Media & Design",
        description:
          "Professional-level video editing, social media management, and high-quality graphic design aligned with your brand identity.",
      },
      {
        title: "Next.js Corporate Identity",
        description:
          "Ultra-fast, SEO-friendly, and scalable modern corporate portfolios built from scratch with Next.js architecture.",
      },
      {
        title: "In-House Business Automation",
        description:
          "Custom desktop/web automation tools and comprehensive management panels built with C# and Python to accelerate internal workflows.",
      },
      {
        title: "Data Dashboards & Reporting",
        description:
          "Custom dashboards and reporting interfaces that transform business data into meaningful metrics and accelerate decision-making.",
      },
    ],
  },
  projects: {
    badge: "PORTFOLIO",
    heading1: "Featured",
    heading2: "Projects",
    freelanceTitle: "Freelance Script & Solution Archive",
    freelanceDesc:
      "Niche industry software developed on-demand on freelance platforms in the past, expanding my portfolio and sector expertise.",
    confidentialBanner:
      "Real mechanical and interface photos cannot be shared due to competition confidentiality policies. Visuals are theoretical AI-generated concepts.",
    confidentialTitle: "Competition Confidentiality",
    confidentialModal:
      "This visual is a theoretical concept generated by AI in compliance with competition rules.",
    showDetails: "Explore System Features",
    hideDetails: "Hide Details",
    items: [
      {
        title: "Stock Analysis Bot",
        category: "AI-POWERED FINANCE",
        description:
          "A sophisticated financial analysis platform predicting stock trends using advanced machine learning models. Employs LightGBM algorithms, Triple-Barrier labeling, and Purged K-Fold Cross-Validation to generate high-precision market signals from Borsa Istanbul (BIST) data.",
        techInfo:
          "Python (LightGBM, Pandas, Scikit-learn) ML Pipeline, TA-Lib for 150+ technical indicators, Kysely query builder, and React-based real-time data visualization dashboard.",
        role: "Full-stack development — backend API, ML pipeline, frontend dashboard, and real-time data streaming.",
        result:
          "Real-time technical analysis for 417+ BIST stocks, AI signal generation, and automatic pattern recognition.",
        expandedContent: [
          {
            title: "Automatic Pattern Detection",
            desc: "Simultaneously scans 13 different technical patterns (Double Top, Head & Shoulders, etc.) on charts and marks them with confidence scores.",
          },
          {
            title: "Machine Learning & Prediction",
            desc: "Generates directional predictions (BUY/SELL/HOLD) using custom labeling techniques (Triple-Barrier) and Ensemble models.",
          },
          {
            title: "Natural Language Processing (NLP)",
            desc: "Simultaneously fetches market news, performs sentiment analysis, and blends results with technical data.",
          },
          {
            title: "Dynamic Risk Management",
            desc: "Autonomously adjusts model decision thresholds based on market volatility to preserve the risk/reward ratio.",
          },
        ],
      },
      {
        title: "VibeKoc",
        category: "AI EDUCATION PLATFORM",
        description:
          "A SaaS EdTech platform that gamifies and personalizes the exam preparation process, featuring a dedicated AI Education Coach for every student. Utilizes behavioral analytics to measure efficiency, identifies knowledge gaps, and provides real-time guidance via a Llama 3/Gemini hybrid AI engine.",
        techInfo:
          "React 19 + Vite, Node.js & TypeScript, MySQL + Kysely, Redis caching, Socket.io real-time duel engine, Google Gemini (2.0 Flash) and OpenAI GPT-4o hybrid integration.",
        role: "Full-stack development — AI coaching engine, Vibe Analytics behavioral analysis algorithms, exam simulator, and gamification systems.",
        result:
          "Success projection (Linear Regression), burnout detector, ÖSYM-style question generation, and 99.9% AI service uptime.",
        expandedContent: [
          {
            title: "Advanced Analytics",
            desc: "30-day success projection via Linear Regression, burnout detection through speed-accuracy correlation, and time efficiency indexing.",
          },
          {
            title: "Smart Exam Simulation",
            desc: "AI-generated questions mimicking real ÖSYM/MEB exam styles and Normal Distribution-based dynamic difficulty scaling.",
          },
          {
            title: "Gamification & Duels",
            desc: "Weekly league cycles from Bronze to Champions League, Socket.io-powered 1v1 real-time duels, and streak mechanics.",
          },
          {
            title: "Institutional (B2B) Analytics",
            desc: "At-risk student detection for schools and tutoring centers, class-level topic heatmaps, and an administrator dashboard.",
          },
        ],
      },
      {
        title: "UMAY Search & Rescue UAV",
        category: "AUTONOMOUS UAV SYSTEM",
        description:
          "An autonomous hexacopter system with dual sensors (Thermal + RGB) and AI, providing aerial strategic support to search-and-rescue teams like AFAD and JAK.",
        techInfo:
          "Live target detection via YOLO-based image processing, Thermal and RGB camera fusion, autonomous route planning.",
        role: "Systems Engineering & Computer Vision — autonomous flight algorithms, sensor integration, and target detection.",
        result:
          "A prototype capable of autonomous transit, precise payload delivery to targets, and live detection even in complete darkness.",
        expandedContent: [
          {
            title: "Autonomous Transit & Reconnaissance",
            desc: "GPS-guided flight to disaster zones and algorithmic search-and-scan route generation without any pilot intervention.",
          },
          {
            title: "Sensor Fusion",
            desc: "High-accuracy live detection in complete darkness, dense fog, or smoke using a hybrid Thermal + RGB camera.",
          },
          {
            title: "Precise Autonomous Intervention",
            desc: "Autonomous, millimeter-precise payload delivery after AI-based detection of marked supply packages.",
          },
          {
            title: "Psychological First Aid",
            desc: "Providing aerial psychological first aid to survivors via the drone's on-board public announcement and audio system.",
          },
        ],
      },
    ],
    labels: {
      techStack: "TECH STACK",
      role: "ROLE",
      result: "RESULT",
      demo: "DEMO",
    },
  },
  marquee: {
    badge: "Sector Solutions",
    heading1: "Digital Modules",
    heading2: "for Every Sector",
    subtitle:
      "Ready-made and customizable digital solutions tailored to your industry.",
    items: [
      { title: "E-Commerce", description: "Online sales platforms and payment integrations" },
      { title: "QR Menu", description: "Digital menu solutions for restaurants and cafes" },
      { title: "Booking System", description: "Online appointment and calendar management" },
      { title: "CRM", description: "Customer relationship management systems" },
      { title: "Education Platform", description: "Online learning and LMS solutions" },
      { title: "Logistics", description: "Cargo tracking and fleet management systems" },
      { title: "Healthcare", description: "Patient tracking and healthcare service management" },
      { title: "Finance", description: "Financial analysis and payment infrastructure" },
    ],
  },
  footer: {
    tagline: "Software Developer",
    copyright: "All rights reserved.",
    visitorCounter: {
      label: "Live Analytics",
      total: "Total Views",
      today: "Today",
    },
  },
  profile: {
    badge: "Developer Profile",
    title: "Software Development Approach",
    bio: "I combine my passion for software with my computer programming education and a full-stack developer vision. I blend technical expertise with creative fields like graphic design and video editing, while maintaining high energy through fitness and bodybuilding discipline. As a developer with both technical and aesthetic perspectives, I focus on producing innovative and optimized solutions.",
    experienceTitle: "Experience",
    educationTitle: "Education",
    skillsTitle: "Technical Skills",
    techStudio: {
      role: "Embedded Systems Intern",
      duration: "9 Months",
      desc: "Work process focused on hardware and software integration. Practical experience in low-level system architectures and optimization.",
    },
    pamukkale: {
      school: "Pamukkale University",
      major: "Computer Programming",
      status: "Ongoing",
    },
    orhan: {
      school: "Orhan Abalioglu MTAL",
      major: "Software Development",
      status: "Graduate",
    },
    skills: {
      languages: "React, React Native, TypeScript, Node.js, C#, Python, SQL",
      ai: "AI-Powered Development (Cursor, Windsurf)",
      multimedia: "Adobe Premiere, After Effects, Photoshop, Illustrator",
    }
  },
};

export default en;
