const en = {
  nav: {
    home: "Home",
    solutions: "Solutions",
    projects: "Projects",
    sectors: "Sectors",
    cta: "Get a Quote",
  },
  clip: {
    tagline: "Software Developer",
  },
  hero: {
    badge: "Full-Stack Developer & GEO Strategist",
    h1_1: "Alperen ",
    h1_2: "Bozkurt",
    h1_3: "",
    h1_4: "",
    subtitle:
      "I blend my passion for software with academic foundations in computer programming and a vision of becoming a comprehensive full-stack developer. Beyond code, I produce projects in creative fields like graphic design and video editing, while deeply researching technological innovations. Maintaining my discipline and energy through fitness, I aim to create innovative and optimized solutions by merging technical excellence with an aesthetic perspective.",
    btnProjects: "Explore Projects",
    btnContact: "Get in Touch",
    scroll: "Scroll",
  },
  solutions: {
    badge: "Strategic Solutions",
    heading1: "Comprehensive Solutions",
    heading2: "for Your Digital Growth",
    subtitle:
      "Take your business to the next level with end-to-end digital transformation services.",
    items: [
      {
        title: "Corporate Web Solutions",
        description:
          "Building modern, enterprise-grade, fully SEO-compliant websites, hosting them on secure servers, and managing all technical maintenance processes.",
      },
      {
        title: "GEO & AI Strategy",
        description:
          "Applying GEO (Generative Engine Optimization) in the age of AI to make companies stand out in next-generation AI-powered search engines.",
      },
      {
        title: "Corporate Media & Design",
        description:
          "Professional-level video editing, social media management, and high-quality graphic design aligned with your brand identity.",
      },
      {
        title: "Next.js Corporate Identity",
        description:
          "Ultra-fast, SEO-friendly, and scalable modern corporate portfolios built from scratch with Next.js architecture.",
      },
      {
        title: "In-House Business Automation",
        description:
          "Custom desktop/web automation tools and comprehensive management panels built with C# and Python to accelerate internal workflows.",
      },
      {
        title: "Data Dashboards & Reporting",
        description:
          "Custom dashboards and reporting interfaces that transform business data into meaningful metrics and accelerate decision-making.",
      },
    ],
  },
  projects: {
    badge: "PORTFOLIO",
    heading1: "Featured",
    heading2: "Projects",
    freelanceTitle: "Freelance Script & Solution Archive",
    freelanceDesc:
      "Niche industry software developed on-demand on freelance platforms in the past, expanding my portfolio and sector expertise.",
    confidentialBanner:
      "Real mechanical and interface photos cannot be shared due to competition confidentiality policies. Visuals are theoretical AI-generated concepts.",
    confidentialTitle: "Competition Confidentiality",
    confidentialModal:
      "This visual is a theoretical concept generated by AI in compliance with competition rules.",
    showDetails: "Explore System Features",
    hideDetails: "Hide Details",
    items: [
      {
        title: "Stock Analysis Bot",
        category: "AI-POWERED FINANCE",
        description:
          "A sophisticated financial analysis platform predicting stock trends using advanced machine learning models. Employs LightGBM algorithms, Triple-Barrier labeling, and Purged K-Fold Cross-Validation to generate high-precision market signals from Borsa Istanbul (BIST) data.",
        techInfo:
          "Python (LightGBM, Pandas, Scikit-learn) ML Pipeline, TA-Lib for 150+ technical indicators, Kysely query builder, and React-based real-time data visualization dashboard.",
        role: "Full-stack development — backend API, ML pipeline, frontend dashboard, and real-time data streaming.",
        result:
          "Real-time technical analysis for 417+ BIST stocks, AI signal generation, and automatic pattern recognition.",
        expandedContent: [
          {
            title: "Automatic Pattern Detection",
            desc: "Simultaneously scans 13 different technical patterns (Double Top, Head & Shoulders, etc.) on charts and marks them with confidence scores.",
          },
          {
            title: "Machine Learning & Prediction",
            desc: "Generates directional predictions (BUY/SELL/HOLD) using custom labeling techniques (Triple-Barrier) and Ensemble models.",
          },
          {
            title: "Natural Language Processing (NLP)",
            desc: "Simultaneously fetches market news, performs sentiment analysis, and blends results with technical data.",
          },
          {
            title: "Dynamic Risk Management",
            desc: "Autonomously adjusts model decision thresholds based on market volatility to preserve the risk/reward ratio.",
          },
        ],
      },
      {
        title: "VibeKoc",
        category: "AI EDUCATION PLATFORM",
        description:
          "A SaaS EdTech platform that gamifies and personalizes the exam preparation process, featuring a dedicated AI Education Coach for every student. Utilizes behavioral analytics to measure efficiency, identifies knowledge gaps, and provides real-time guidance via a Llama 3/Gemini hybrid AI engine.",
        techInfo:
          "React 19 + Vite, Node.js & TypeScript, MySQL + Kysely, Redis caching, Socket.io real-time duel engine, Google Gemini (2.0 Flash) and OpenAI GPT-4o hybrid integration.",
        role: "Full-stack development — AI coaching engine, Vibe Analytics behavioral analysis algorithms, exam simulator, and gamification systems.",
        result:
          "Success projection (Linear Regression), burnout detector, ÖSYM-style question generation, and 99.9% AI service uptime.",
        expandedContent: [
          {
            title: "Advanced Analytics",
            desc: "30-day success projection via Linear Regression, burnout detection through speed-accuracy correlation, and time efficiency indexing.",
          },
          {
            title: "Smart Exam Simulation",
            desc: "AI-generated questions mimicking real ÖSYM/MEB exam styles and Normal Distribution-based dynamic difficulty scaling.",
          },
          {
            title: "Gamification & Duels",
            desc: "Weekly league cycles from Bronze to Champions League, Socket.io-powered 1v1 real-time duels, and streak mechanics.",
          },
          {
            title: "Institutional (B2B) Analytics",
            desc: "At-risk student detection for schools and tutoring centers, class-level topic heatmaps, and an administrator dashboard.",
          },
        ],
      },
      {
        title: "UMAY Search & Rescue UAV",
        category: "AUTONOMOUS UAV SYSTEM",
        description:
          "An autonomous hexacopter system with dual sensors (Thermal + RGB) and AI, providing aerial strategic support to search-and-rescue teams like AFAD and JAK.",
        techInfo:
          "Live target detection via YOLO-based image processing, Thermal and RGB camera fusion, autonomous route planning.",
        role: "Systems Engineering & Computer Vision — autonomous flight algorithms, sensor integration, and target detection.",
        result:
          "A prototype capable of autonomous transit, precise payload delivery to targets, and live detection even in complete darkness.",
        expandedContent: [
          {
            title: "Autonomous Transit & Reconnaissance",
            desc: "GPS-guided flight to disaster zones and algorithmic search-and-scan route generation without any pilot intervention.",
          },
          {
            title: "Sensor Fusion",
            desc: "High-accuracy live detection in complete darkness, dense fog, or smoke using a hybrid Thermal + RGB camera.",
          },
          {
            title: "Precise Autonomous Intervention",
            desc: "Autonomous, millimeter-precise payload delivery after AI-based detection of marked supply packages.",
          },
          {
            title: "Psychological First Aid",
            desc: "Providing aerial psychological first aid to survivors via the drone's on-board public announcement and audio system.",
          },
        ],
      },
      {
        title: "VibeFlow",
        category: "AI CODING OPTIMIZATION",
        description:
          "A local, editor-agnostic context optimization sidecar for AI coding workflows. It watches a project, builds a compact AST-aware memory, prunes unrelated files, and sends only the relevant context to the model to optimize token usage.",
        techInfo:
          "Local FastAPI server, watchdog-based file watching, tree-sitter parsing, ChromaDB vector cache, and CLI-first terminal management.",
        role: "Product design and development - context builder, watcher engine, CLI commands, optimization profiles, and agent integration workflow.",
        result:
          "A local developer tool that helps coding agents work with selected, summarized context instead of reading the entire repository.",
        expandedContent: [
          {
            title: "Token Savings",
            desc: "Uses semantic pruning, skeletonization, and budget caps to keep model context compact.",
          },
          {
            title: "Local Sidecar API",
            desc: "Provides editor-agnostic /context, /index, and /settings endpoints through FastAPI.",
          },
          {
            title: "Live Project Watching",
            desc: "Tracks file changes with watchdog and keeps the project index warm during development.",
          },
          {
            title: "Agent-Friendly Output",
            desc: "Produces model-ready context and a diff-focused output contract for coding agents.",
          },
        ],
      },
      {
        title: "Flowy",
        category: "MUSIC STREAMING APP",
        description:
          "A web and desktop-focused music streaming application that delivers a modern listening experience powered by YouTube. It combines a premium Spotify-like interface with Electron support to offer both browser and desktop usage from a single codebase.",
        techInfo:
          "Next.js, Electron, React 19, Tailwind CSS, Framer Motion, YouTube search/playback flow, and client-side player control architecture.",
        role: "Product design and development - player experience, UI architecture, desktop wrapper integration, and music discovery flows.",
        result:
          "A dark-themed, performance-oriented music app that ships both web and desktop experiences from one codebase.",
        expandedContent: [
          {
            title: "Cross-Platform Experience",
            desc: "Combines a Next.js interface with Electron to unify browser and native desktop usage in one product experience.",
          },
          {
            title: "Modern Player UI",
            desc: "Provides a full-screen player, bottom playback bar, library structure, and fluid interfaces that feel like a premium music app.",
          },
          {
            title: "YouTube-Powered Catalog Flow",
            desc: "Integrates YouTube-based search and playback logic into the app flow to access a broad music catalog.",
          },
          {
            title: "Discovery and Mixes",
            desc: "Builds sticky user flows through daily mixes, recommendations, and library-first navigation patterns.",
          },
        ],
      },
    ],
    labels: {
      techStack: "TECH STACK",
      role: "ROLE",
      result: "RESULT",
      demo: "DEMO",
      github: "GITHUB",
    },
  },
  marquee: {
    badge: "Sector Solutions",
    heading1: "Digital Modules",
    heading2: "for Every Sector",
    subtitle:
      "Ready-made and customizable digital solutions tailored to your industry.",
    items: [
      { title: "E-Commerce", description: "Online sales platforms and payment integrations" },
      { title: "QR Menu", description: "Digital menu solutions for restaurants and cafes" },
      { title: "Booking System", description: "Online appointment and calendar management" },
      { title: "CRM", description: "Customer relationship management systems" },
      { title: "Education Platform", description: "Online learning and LMS solutions" },
      { title: "Logistics", description: "Cargo tracking and fleet management systems" },
      { title: "Healthcare", description: "Patient tracking and healthcare service management" },
      { title: "Finance", description: "Financial analysis and payment infrastructure" },
    ],
  },
  footer: {
    tagline: "Software Developer",
    copyright: "All rights reserved.",
    visitorCounter: {
      label: "Live Analytics",
      total: "Total Views",
      today: "Today",
    },
  },
  profile: {
    badge: "Developer Profile",
    title: "Software Development Approach",
    bio: "I combine my passion for the software world with my computer programming education and a vision of becoming a fully-equipped full-stack developer. I specialize in AI integration, financial data analytics, and the development of high-performance web applications. While I engage in visual storytelling with Premiere Pro and After Effects on the creative side, I create added value on the technical side with the modern JavaScript ecosystem and machine learning models. I always aim to produce more innovative, optimized, and aesthetic solutions.",
    experienceTitle: "Work Experience",
    educationTitle: "Education",
    skillsTitle: "Technical Expertise",
    techStudio: {
      role: "Full-Stack Developer",
      duration: "2023 - Present",
      desc: "Developing end-to-end enterprise solutions using modern web technologies (React 19, Next.js 15, Node.js). Optimizing data processing workflows with microservices architecture, RESTful API design, and database management. Prioritizing User Experience (UX) through interface performance optimizations and scalable architectural designs.",
    },
    pamukkale: {
      school: "Pamukkale University",
      major: "Computer Programming",
      status: "Ongoing",
    },
    orhan: {
      school: "Orhan Abalioglu MTAL",
      major: "Software Development",
      status: "Graduate",
    },
    skills: {
      languages: "TypeScript, JavaScript, Python, Node.js, React 19, Next.js 15, MySQL, PostgreSQL, Redis, Tailwind CSS v4",
      ai: "Generative Engine Optimization (GEO), LLM Integration (OpenAI, Gemini), Machine Learning (Scikit-learn, LightGBM), Prompt Engineering",
      multimedia: "Adobe Premiere Pro, After Effects, Photoshop, Illustrator, Visual Storytelling, Video Editing & Motion Graphics",
    }
  },
};

export default en;
